#!/bin/bash

#for f in /usr/local/Cellar/figlet/2.2.5/share/figlet/fonts/*.flf
#do
# echo "$(basename $f .flf)"
# figlet -f $(basename $f .flf) Dr. Squiggles
#done

echo "   ,'\"\"\`.      ,'\"\"\`.      ,'\"\"\`.      ,'\"\"\`.      ,'\"\"\`.   "
echo "  / _  _ \\    / _  _ \\    / _  _ \\    / _  _ \\    / _  _ \\  "
echo "  |(@)(@)|    |(@)(@)|    |(@)(@)|    |(@)(@)|    |(@)(@)|  "
echo "  )  __  (    )  __  (    )  __  (    )  __  (    )  __  (  "
echo " /,'))((\`.\\  /,'))((\`.\\  /,'))((\`.\\  /,'))((\`.\\  /,'))((\`.\\ "
echo "(( ((  )) ))(( ((  )) ))(( ((  )) ))(( ((  )) ))(( ((  )) ))"
echo " \`\\ \`)(' /'  \`\\ \`)(' /'  \`\\ \`)(' /'  \`\\ \`)(' /'  \`\\ \`)(' /' "
echo " ____         ____              _             _           "
echo "|  _ \\ _ __  / ___|  __ _ _   _(_) __ _  __ _| | ___  ___ "
echo "| | | | '__| \\___ \\ / _\` | | | | |/ _\` |/ _\` | |/ _ \\/ __|"
echo "| |_| | | _   ___) | (_| | |_| | | (_| | (_| | |  __/\\__ \\"
echo "|____/|_|(_) |____/ \\__, |\\__,_|_|\\__, |\\__, |_|\\___||___/"
echo "                       |_|        |___/ |___/    "
echo "On startup, this robot tries to connect to a network named 'Dr_Squiggles'"
echo "with password 'isthebest!'. You can make such a network with your phone."
echo "Then, you can ssh here with 'ssh $(hostname)'. The command 'sq' starts"
echo "the main beat-tracking, rhythm-generating software that defines this robot."
echo "the source code for sq is in '/home/pi/Dr_Squiggles'. This code is"
echo "automatically pulled from Github and compiled on boot, given that the"
echo "internet is reachable. More info is in the repository, at "
echo "https://github.com/michaelkrzyzaniak/Dr_Squiggles"

